web: cd services/auth && node src/main server
expireSentry: cd services/auth && node src/main expire-sentry
purgeExpiredClients: cd services/auth && node src/main purge-expired-clients
write-docs: cd services/auth && node src/main writeDocs
