defaults:
test:
  test:
    testBucket: "test-bucket-for-any-garbage"
  aws:
    accessKeyId:        "..."
    secretAccessKey:    "..."
  pulse:
    username:           "..."
    password:           "..."
  gcp:
    credentials:        "..."
