enum ProvisionerStability {
  EXPERIMENTAL
  STABLE
  DEPRECATED
}

type Provisioner {
  provisionerId: String!
  stability: ProvisionerStability!
  description: String!
  expires: DateTime!
  lastDateActive: DateTime!
  # Note: This field will trigger an additional request.
  workerTypes(provisionerId: String = provisionerId, connection: PageConnection): WorkerTypesConnection
  # Note: This field will trigger an additional request.
  workerType(provisionerId: String = provisionerId, workerType: String!): WorkerType
}

type ProvisionersEdge implements Edge {
  cursor: String
  node: Provisioner
}

type ProvisionersConnection implements Connection {
  pageInfo: PageInfo
  edges: [ProvisionersEdge]
}

extend type Query {
  provisioner(provisionerId: String!): Provisioner
  provisioners(connection: PageConnection): ProvisionersConnection
}

# TODO: Provisioner mutations
#extend type Mutation {}
