type WorkerManagerWorkerPoolSummary {
    workerPoolId: String!
    description: String
    owner: String!
    providerId: String!
    config: JSON
    emailOnError: Boolean!
    currentCapacity: Int!
    requestedCount: Int!
    runningCount: Int!
    stoppingCount: Int!
    stoppedCount: Int!
    requestedCapacity: Int!
    runningCapacity: Int!
    stoppingCapacity: Int!
    stoppedCapacity: Int!
    pendingTasks: Int #this value comes from a separate request to queue
}

type WMWorker {
  workerPoolId: String!
  workerGroup: String!
  workerId: String!
  providerId: String!
  state: String!
  created: DateTime!
  expires: DateTime!
  capacity: Int!
  lastModified: DateTime!
  lastChecked: DateTime!
  launchConfigId: String
}

extend type Query {
    WorkerPool(workerPoolId: String!): WorkerManagerWorkerPoolSummary

    WorkerManagerWorker(workerPoolId: String!, workerGroup: String!, workerId: ID!): WMWorker
}
