type WorkerManagerWorkerPoolSummary {
    workerPoolId: String!
    description: String
    owner: String!
    providerId: String!
    config: JSON
    emailOnError: Boolean!
    currentCapacity: Int!
    requestedCount: Int!
    runningCount: Int!
    stoppingCount: Int!
    stoppedCount: Int!
    requestedCapacity: Int!
    runningCapacity: Int!
    stoppingCapacity: Int!
    stoppedCapacity: Int!
    pendingTasks: Int #this value comes from a separate request to queue
}

type WorkerManagerWorkerPoolSummaryConnection implements Connection {
  pageInfo: PageInfo
  edges: [WorkerManagerWorkerPoolSummaryEdge]
}

type WorkerManagerWorkerPoolSummaryEdge implements Edge {
  cursor: String
  node: WorkerManagerWorkerPoolSummary
}

type WorkerPoolErrorTotals {
  total: Int!
  hourly: JSON!
  daily: JSON!
  title: JSON!
  code: JSON!
  workerPool: JSON!
  launchConfig: JSON!
}

type WorkerManagerErrorsStats {
  workerPoolId: String!
  totals: WorkerPoolErrorTotals!
}

type WMWorker {
  workerPoolId: String!
  workerGroup: String!
  workerId: String!
  providerId: String!
  state: String!
  created: DateTime!
  expires: DateTime!
  capacity: Int!
  lastModified: DateTime!
  lastChecked: DateTime!
  launchConfigId: String
}

extend type Query {
    WorkerManagerWorkerPoolSummaries(connection: PageConnection, searchTerm: String): WorkerManagerWorkerPoolSummaryConnection!

    WorkerManagerErrorsStats(workerPoolId: String): WorkerManagerErrorsStats!

    WorkerPool(workerPoolId: String!): WorkerManagerWorkerPoolSummary

    WorkerManagerWorker(workerPoolId: String!, workerGroup: String!, workerId: ID!): WMWorker
}
