export default {
  version: 0,
  $schema: 'http://schemas.taskcluster.net/base/v1/api-reference.json#',
  title: 'Fake API',
  description: 'Fake API',
  baseUrl: 'https://fake.taskcluster.net/v1',
  entries: [
    {
      type: 'function',
      method: 'get',
      route: '/get-test',
      query: [],
      args: [],
      name: 'get',
      stability: 'experimental',
      title: 'Test Get',
      description: 'Place we can call to test GET',
      scopes: [],
    },
    {
      type: 'function',
      method: 'post',
      route: '/post-test',
      query: [],
      args: [],
      name: 'post',
      stability: 'experimental',
      title: 'Test Post',
      description: 'Place we can call to test POST',
      scopes: [],
      input: 'http://schemas.taskcluster.net/nothing.json'
    },
    {
      type: 'function',
      method: 'post',
      route: '/post-param/<param>',
      query: [],
      args: ['param'],
      name: 'postParam',
      stability: 'experimental',
      title: 'Test Post Param',
      description: 'Place we can call to test POST with params',
      scopes: [],
      input: 'http://schemas.taskcluster.net/nothing.json'
    },
    {
      type: 'function',
      method: 'post',
      route: '/post-param-query/<param>',
      query: ['option'],
      args: ['param'],
      name: 'postParamQuery',
      stability: 'experimental',
      title: 'Test Post Param Query',
      description: 'Place we can call to test POST with params and a query',
      scopes: [],
      input: 'http://schemas.taskcluster.net/nothing.json'
    },
    {
      type: 'function',
      method: 'get',
      route: '/url-param/<param>/list',
      query: [],
      args: ['param'],
      name: 'param',
      stability: 'experimental',
      title: 'Test Params',
      description: 'Place we can call to test url parameters',
      scopes: [],
    },
    {
      type: 'function',
      method: 'get',
      route: '/url-param2/<param1>/<param2>/list',
      query: [],
      args: ['param1', 'param2'],
      name: 'param2',
      stability: 'experimental',
      title: 'Test Params',
      description: 'Place we can call to test url parameters',
      scopes: [],
    },
    {
      type: 'function',
      method: 'get',
      route: '/query/test',
      query: ['option'],
      args: [],
      name: 'query',
      stability: 'experimental',
      title: 'Test Query string options',
      description: 'Place we can call to test query string',
      scopes: [],
    },
    {
      type: 'function',
      method: 'get',
      route: '/param-query/<param>',
      query: ['option'],
      args: ['param'],
      name: 'paramQuery',
      stability: 'experimental',
      title: 'Test Query string options with params',
      description: 'Place we can call to test query string with params',
      scopes: [],
    }
  ],
};
