// This source code file is AUTO-GENERATED by github.com/taskcluster/jsonschema2go

package tcobject

import (
	tcclient "github.com/taskcluster/taskcluster/v38/clients/client-go"
)

type (
	// Representation of the object entry to insert.
	UploadObjectRequest struct {

		// Date at which this entry expires from the object table.
		Expires tcclient.Time `json:"expires"`

		// Project identifier.
		ProjectID string `json:"projectId"`
	}
)
