#!/bin/bash -xveu

cd "$(dirname "${0}")"
rm -rf "${GOPATH}"/bin/{hack,generatemodel}
rm -rf "${GOPATH}"/pkg/*/github.com/*/taskcluster-client-go
go clean ./...
go fmt ./...
# go get -v -u ./...
go generate ./...
go install -v ./...
