web:                    node src/main server
claimReaper:            node src/main claim-reaper
deadlineReaper:         node src/main deadline-reaper
dependencyResolver:     node src/main dependency-resolver
expireArtifacts:        node src/main expire-artifacts
expireTask:             node src/main expire-tasks
expireTaskGroups:       node src/main expire-task-groups
expireTaskGroupMembers: node src/main expire-task-group-members
expireTaskGroupSizes:   node src/main expire-task-group-sizes
expireTaskDependency    node src/main expire-task-dependency
expireTaskRequirement   node src/main expire-task-requirement
expireQueues:           node src/main expire-queues
expireWorkerInfo:       node src/main expire-worker-info
