web: cd services/hooks && node src/main.js server
scheduler: cd services/hooks && node src/main.js scheduler
write-docs: cd services/hooks && node src/main.js writeDocs
listeners: cd services/hooks && node src/main.js listeners
