#!/bin/bash

# Find instance storage devices
devices=$(ls /dev/xvd* | grep -v '/dev/xvda');

# Unmount block-device if already mounted, the first block-device always is
for d in $devices; do umount $d || true; done

# Create volume group containing all instance storage devices
echo $devices | xargs vgcreate instance_storage

# Create logical volume with all storage
lvcreate -l 100%VG -n all instance_storage

# Format logical volume with ext4
mkfs.ext4 /dev/instance_storage/all

# Mount on /mnt
mount /dev/instance_storage/all /mnt

mkdir -p /mnt/var/lib/docker
mkdir -p /mnt/docker-tmp
export TMPDIR="/mnt/docker-tmp"
export DOCKER_OPTS=" -g /mnt/var/lib/docker -s aufs"
