from ubuntu
maintainer James Lal <james@lightsofapollo.com>

# This docker file is a test image for the host to target.
# The general idea is we can interchange these hosts but we need
# At least one consistent one for testing the host itself.

# General setup stuff which is probably optional
run adduser -m tester
env HOME /home/tester
