module.exports = {
  Boolean: 'boolean',
  Number: 'number',
  PositiveInteger: 'positive-integer',
  Date: 'date',
  UUID: 'uuid',
  SlugId: 'slug-id',
  BaseBufferType: 'base-buffer-type',
  Blob: 'blob',
  JSON: 'json',
  Schema: 'schema',
  EncryptedBlob: 'encrypted-blob',
  EncryptedText: 'encrypted-text',
  EncryptedJSON: 'encrypted-json',
  EncryptedSchema: 'encrypted-schema',
  SlugIdArray: 'slug-id-array',
  String: 'string',
  Text: 'text',
};
