#!/bin/bash -vex

# Wait for cloud-init to finish initializing.
while [ ! -e /var/lib/cloud/instance/boot-finished ]; do
    echo "waiting on cloud-init to finish..."
    sleep 1
done

if [ ! -e /mnt/var/lib/docker ]; then
    echo "/mnt/var/lib/docker not present; look in cloud-init logs for initialization errors"
    exit 1
fi

export TMPDIR="/mnt/docker-tmp"
export DOCKER_OPTS=" -g /mnt/var/lib/docker -s overlay2 --icc=false --iptables=true"
