#!/bin/bash -vex

# Create logical volume
# Do not attempt to create if volume already exists (upstart respawn).
if ! lvdisplay | grep instance_storage;
then
    echo "Creating logical volume 'instance_storage'"
    # Find instance storage devices
    devices=$(ls /dev/xvd* | grep -v '/dev/xvda');

    # Unmount block-device if already mounted, the first block-device always is
    for d in $devices; do umount $d || true; done

    # Create volume group containing all instance storage devices
    echo $devices | xargs vgcreate instance_storage

    # Create logical volume with all storage
    lvcreate -l 100%VG -n all instance_storage
else
    echo "Logical volume 'instance_storage' already exists"
fi

echo "Formating 'instance_storage' as ext4"

# Format logical volume with ext4
if ! mkfs.ext4 /dev/instance_storage/all;
then
    echo "Could not format 'instance_storage' as ext4."
    # Wait for the logical volume to become ready to be formatted.
    # Small wait is better than zombie node.
    sleep 5
    exit 1
else
    echo "Succesfully formated 'instance_storage' as ext4."
fi

echo "Mounting logical volume"
# Mount on /mnt
mount /dev/instance_storage/all /mnt

echo "Creating docker specific directories"
mkdir -p /mnt/var/lib/docker
mkdir -p /mnt/docker-tmp
mkdir -p /mnt/var/cache/docker-worker

export TMPDIR="/mnt/docker-tmp"
export DOCKER_OPTS=" -g /mnt/var/lib/docker -s aufs"
