import React, { Component } from 'react';
import { Auth } from '@taskcluster/client-web';
import { scopeIntersection } from 'taskcluster-lib-scopes';
import { parse } from 'qs';
import Typography from '@material-ui/core/Typography';
import Spinner from '../../components/Spinner';
import AuthConsent from '../../components/AuthConsent';
import Dashboard from '../../components/Dashboard';
import { withAuth } from '../../utils/Auth';
import { withTaskclusterClient } from '../../utils/TaskclusterClient';
import fromNowJSON from '../../utils/fromNowJSON';

@withAuth
@withTaskclusterClient
export default class ThirdPartyLogin extends Component {
  query = this.props.location.search.slice(1);

  parsedQuery = parse(this.query);

  state = {
    formData: null,
    currentScopes: null,
    loading: false,
    error: null,
  };

  static getDerivedStateFromProps(props, state) {
    const {
      user,
      location: { search },
    } = props;
    const { currentScopes } = state;
    const query = parse(search.slice(1));
    const scopes = (query.scope || '').split(' ');
    const registeredClientId = query.client_id;

    if (
      !user ||
      state.formData ||
      !Array.isArray(currentScopes) ||
      !query.transactionID
    ) {
      return null;
    }

    return {
      formData: {
        ...state.formData,
        scopes: scopeIntersection(scopes, currentScopes),
        expires: fromNowJSON(query.expires),
        description: `Client generated by ${user.credentials.clientId} for OAuth2 Client ${registeredClientId}`,
      },
    };
  }

  get authClient() {
    return this.props.createTaskclusterClient({ Class: Auth });
  }

  componentDidMount() {
    this.loadCurrentScopes();
  }

  componentDidUpdate(prevProps) {
    if (this.props.user !== prevProps.user) {
      this.loadCurrentScopes();
    }
  }

  loadCurrentScopes = async () => {
    if (!this.props.user) {
      this.setState({ currentScopes: null, loading: false, error: null });

      return;
    }

    this.setState({ loading: true, error: null });

    try {
      const { scopes } = await this.authClient.currentScopes();

      this.setState({ currentScopes: scopes, loading: false, error: null });
    } catch (error) {
      this.setState({ currentScopes: null, loading: false, error });
    }
  };

  handleExpirationChange = expires => {
    this.setState({
      formData: {
        ...this.state.formData,
        expires,
      },
    });
  };

  handleInputChange = ({ target: { name, value } }) => {
    this.setState({
      formData: {
        ...this.state.formData,
        [name]: value,
      },
    });
  };

  handleScopesChange = scopes => {
    this.setState({
      formData: {
        ...this.state.formData,
        scopes,
      },
    });
  };

  render() {
    const { user } = this.props;
    const { formData, loading } = this.state;
    const hasValidRedirect = !!this.parsedQuery.redirect_uri;
    const getOrigin = () => {
      const { origin } = new URL(
        decodeURIComponent(this.parsedQuery.redirect_uri)
      );

      return origin;
    };

    return (
      <Dashboard title="Third Party Login">
        {loading && <Spinner loading />}
        {formData && (
          <AuthConsent
            transactionID={this.parsedQuery.transactionID}
            registeredClientId={this.parsedQuery.client_id}
            clientId={this.parsedQuery.clientId}
            onExpirationChange={this.handleExpirationChange}
            onInputChange={this.handleInputChange}
            onScopesChange={this.handleScopesChange}
            formData={formData}
          />
        )}
        {!user && hasValidRedirect && (
          <Typography variant="subtitle1">
            Sign in to provide credentials to <code>{getOrigin()}</code>
          </Typography>
        )}
        {!hasValidRedirect && (
          <Typography variant="subtitle2">Invalid request</Typography>
        )}
      </Dashboard>
    );
  }
}
