module.exports = {
  Clients: { serviceName: 'auth', path: 'services/auth/src/data.js' },
  // TaskclusterGithubBuilds: { serviceName: '', path: '' },
  // TaskclusterIntegrationOwners: { serviceName: '', path: '' },
  // TaskclusterChecksToTasks: { serviceName: '', path: '' },
  // TaskclusterCheckRuns: { serviceName: '', path: '' },
  // Hooks: { serviceName: '', path: '' },
  // Queues: { serviceName: '', path: '' },
  // LastFire3: { serviceName: '', path: '' },
  // IndexedTasks: { serviceName: '', path: '' },
  // Namespaces: { serviceName: '', path: '' },
  // DenylistedNotification: { serviceName: '', path: '' },
  // CachePurges: { serviceName: '', path: '' },
  // QueueTasks: { serviceName: '', path: '' },
  // QueueArtifacts: { serviceName: '', path: '' },
  // QueueTaskGroups: { serviceName: '', path: '' },
  // QueueTaskGroupMembers: { serviceName: '', path: '' },
  // QueueTaskGroupActiveSets: { serviceName: '', path: '' },
  // QueueTaskRequirement: { serviceName: '', path: '' },
  // QueueTaskDependency: { serviceName: '', path: '' },
  // QueueWorker: { serviceName: '', path: '' },
  // QueueWorkerType: { serviceName: '', path: '' },
  // QueueProvisioner: { serviceName: '', path: '' },
  // Secrets: { serviceName: '', path: '' },
  // AuthorizationCodesTable: { serviceName: '', path: '' },
  // AccessTokenTable: { serviceName: '', path: '' },
  // SessionStorageTable: { serviceName: '', path: '' },
  // GithubAccessTokenTable: { serviceName: '', path: '' },
  // WMWorkers: { serviceName: '', path: '' },
  // WMWorkerPools: { serviceName: '', path: '' },
  // WMWorkerPoolErrors: { serviceName: '', path: '' },
};
