// This source code file is AUTO-GENERATED by github.com/taskcluster/jsonschema2go

package pulse

type (
	// Namespace creation request
	//
	// See http://schemas.taskcluster.net/pulse/v1/namespace-request.json#
	NamespaceCreationRequest struct {

		// The contact Information
		//
		// See http://schemas.taskcluster.net/pulse/v1/namespace-request.json#/properties/contact
		Contact struct {

			// The contact id (eg. username, email address)
			//
			// See http://schemas.taskcluster.net/pulse/v1/namespace-request.json#/properties/contact/properties/id
			ID string `json:"id,omitempty"`

			// The contact method (eg. irc, email)
			//
			// See http://schemas.taskcluster.net/pulse/v1/namespace-request.json#/properties/contact/properties/method
			Method string `json:"method,omitempty"`
		} `json:"contact"`
	}

	// Rabbit overview response
	//
	// See http://schemas.taskcluster.net/pulse/v1/rabbit-overview.json#
	RabbitOverviewResponse struct {

		// The name of the cluster
		//
		// Min length: 1
		//
		// See http://schemas.taskcluster.net/pulse/v1/rabbit-overview.json#/properties/cluster_name
		Cluster_Name string `json:"cluster_name"`

		// The version of the management
		//
		// Min length: 1
		//
		// See http://schemas.taskcluster.net/pulse/v1/rabbit-overview.json#/properties/management_version
		Management_Version string `json:"management_version"`

		// The version of RabbitMQ
		//
		// Min length: 1
		//
		// See http://schemas.taskcluster.net/pulse/v1/rabbit-overview.json#/properties/rabbitmq_version
		Rabbitmq_Version string `json:"rabbitmq_version"`
	}
)
