export default {
  RUNNING: 'info',
  PENDING: 'default',
  SCHEDULED: 'default',
  UNSCHEDULED: 'default',
  COMPLETED: 'success',
  FAILED: 'error',
  EXCEPTION: 'warning',
  DEADLINE_EXCEEDED: 'warning',
  CANCELED: 'info',
  SUPERSEDED: 'default',
  CLAIM_EXPIRED: 'info',
  WORKER_SHUTDOWN: 'warning',
  MALFORMED_PAYLOAD: 'error',
  RESOURCE_UNAVAILABLE: 'error',
  INTERNAL_ERROR: 'error',
  INTERMITTENT_TASK: 'warning',
  RETRY: 'info',
  TASK_RETRY: 'info',
  RERUN: 'info',
};
