{{- if and (eq (.Values.ingressType | default "") "gateway") (hasPrefix "gke-" (.Values.gatewayClassName | default "")) (not (has "healthcheckpolicy" .Values.skipResourceTypes)) -}}
apiVersion: networking.gke.io/v1
kind: HealthCheckPolicy
metadata:
  name: taskcluster-index-web-hc
  labels:
    app.kubernetes.io/name: taskcluster-index-web-hc
    app.kubernetes.io/instance: '{{ .Release.Name }}'
    app.kubernetes.io/component: taskcluster-index-web-hc-healthcheckpolicy
    app.kubernetes.io/part-of: taskcluster
spec:
  default:
    config:
      type: HTTP
      httpHealthCheck:
        requestPath: /api/index/v1/ping
        port: 8080
  targetRef:
    group: ''
    kind: Service
    name: taskcluster-index
{{- end }}
