// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.

import Client from '../Client';

export default class Object extends Client {
  constructor(options = {}) {
    super({
      serviceName: 'object',
      serviceVersion: 'v1',
      exchangePrefix: '',
      ...options,
    });
    this.ping.entry = {"args":[],"category":"Ping Server","method":"get","name":"ping","query":[],"route":"/ping","stability":"stable","type":"function"}; // eslint-disable-line
    this.uploadObject.entry = {"args":["name","projectId"],"category":"Backend","method":"post","name":"uploadObject","query":[],"route":"/upload/<name>/<projectId>","scopes":"object:upload:<name>/<projectId>","stability":"experimental","type":"function"}; // eslint-disable-line
  }
  /* eslint-disable max-len */
  // Respond without doing anything.
  // This endpoint is used to check that the service is up.
  /* eslint-enable max-len */
  ping(...args) {
    this.validate(this.ping.entry, args);

    return this.request(this.ping.entry, args);
  }
  /* eslint-disable max-len */
  // Upload backend data.
  /* eslint-enable max-len */
  uploadObject(...args) {
    this.validate(this.uploadObject.entry, args);

    return this.request(this.uploadObject.entry, args);
  }
}
