// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.

import Client from '../Client';

export default class WebServer extends Client {
  constructor(options = {}) {
    super({
      serviceName: 'web-server',
      serviceVersion: 'v1',
      exchangePrefix: '',
      ...options,
    });
    this.ping.entry = {"args":[],"category":"Monitoring","method":"get","name":"ping","query":[],"route":"/ping","stability":"stable","type":"function"}; // eslint-disable-line
    this.lbheartbeat.entry = {"args":[],"category":"Monitoring","method":"get","name":"lbheartbeat","query":[],"route":"/__lbheartbeat__","stability":"stable","type":"function"}; // eslint-disable-line
    this.version.entry = {"args":[],"category":"Monitoring","method":"get","name":"version","query":[],"route":"/__version__","stability":"stable","type":"function"}; // eslint-disable-line
    this.taskGroupProfile.entry = {"args":["taskGroupId"],"category":"Profiler","method":"get","name":"taskGroupProfile","query":[],"route":"/task-group/<taskGroupId>/profile","stability":"experimental","type":"function"}; // eslint-disable-line
    this.taskProfile.entry = {"args":["taskId"],"category":"Profiler","method":"get","name":"taskProfile","query":[],"route":"/task/<taskId>/profile","stability":"experimental","type":"function"}; // eslint-disable-line
    this.heartbeat.entry = {"args":[],"category":"Monitoring","method":"get","name":"heartbeat","query":[],"route":"/__heartbeat__","stability":"stable","type":"function"}; // eslint-disable-line
  }
  /* eslint-disable max-len */
  // Respond without doing anything.
  // This endpoint is used to check that the service is up.
  /* eslint-enable max-len */
  ping(...args) {
    this.validate(this.ping.entry, args);

    return this.request(this.ping.entry, args);
  }
  /* eslint-disable max-len */
  // Respond without doing anything.
  // This endpoint is used to check that the service is up.
  /* eslint-enable max-len */
  lbheartbeat(...args) {
    this.validate(this.lbheartbeat.entry, args);

    return this.request(this.lbheartbeat.entry, args);
  }
  /* eslint-disable max-len */
  // Respond with the JSON version object.
  // https://github.com/mozilla-services/Dockerflow/blob/main/docs/version_object.md
  /* eslint-enable max-len */
  version(...args) {
    this.validate(this.version.entry, args);

    return this.request(this.version.entry, args);
  }
  /* eslint-disable max-len */
  // Generate a Firefox Profiler–compatible profile from a task group.
  // The profile contains scheduling and execution timing for all tasks.
  /* eslint-enable max-len */
  taskGroupProfile(...args) {
    this.validate(this.taskGroupProfile.entry, args);

    return this.request(this.taskGroupProfile.entry, args);
  }
  /* eslint-disable max-len */
  // Generate a Firefox Profiler–compatible profile from a task's log output.
  // Parses `public/logs/live.log` (or `live_backing.log`) for timing data.
  /* eslint-enable max-len */
  taskProfile(...args) {
    this.validate(this.taskProfile.entry, args);

    return this.request(this.taskProfile.entry, args);
  }
  /* eslint-disable max-len */
  // Respond with a service heartbeat.
  // This endpoint is used to check on backing services this service
  // depends on.
  /* eslint-enable max-len */
  heartbeat(...args) {
    this.validate(this.heartbeat.entry, args);

    return this.request(this.heartbeat.entry, args);
  }
}
