// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.

import Client from '../Client';

export default class WorkerManagerEvents extends Client {
  constructor(options = {}) {
    super({
      serviceName: 'worker-manager',
      serviceVersion: 'v1',
      exchangePrefix: 'exchange/taskcluster-worker-manager/v1/',
      ...options,
    });
  }
  /* eslint-disable max-len */
  // Whenever the api receives a request to create aworkerType, a message is posted to this exchange anda provider can act upon it.
  /* eslint-enable max-len */
  workerTypeCreated(pattern) {
    const entry = {"exchange":"workertype-created","name":"workerTypeCreated","routingKey":[{"constant":"primary","multipleWords":false,"name":"routingKeyKind","required":true},{"multipleWords":true,"name":"reserved","required":false}],"schema":"v1/pulse-workertype-message.json#","type":"topic-exchange"}; // eslint-disable-line

    return this.normalizePattern(entry, pattern);
  }
  /* eslint-disable max-len */
  // Whenever the api receives a request to update aworkerType, a message is posted to this exchange anda provider can act upon it.
  /* eslint-enable max-len */
  workerTypeUpdated(pattern) {
    const entry = {"exchange":"workertype-updated","name":"workerTypeUpdated","routingKey":[{"constant":"primary","multipleWords":false,"name":"routingKeyKind","required":true},{"multipleWords":true,"name":"reserved","required":false}],"schema":"v1/pulse-workertype-message.json#","type":"topic-exchange"}; // eslint-disable-line

    return this.normalizePattern(entry, pattern);
  }
  /* eslint-disable max-len */
  // Whenever the api receives a request to delete aworkerType, a message is posted to this exchange anda provider can act upon it.
  /* eslint-enable max-len */
  workerTypeDeleted(pattern) {
    const entry = {"exchange":"workertype-deleted","name":"workerTypeDeleted","routingKey":[{"constant":"primary","multipleWords":false,"name":"routingKeyKind","required":true},{"multipleWords":true,"name":"reserved","required":false}],"schema":"v1/pulse-workertype-message.json#","type":"topic-exchange"}; // eslint-disable-line

    return this.normalizePattern(entry, pattern);
  }
}
