// This file doesn't actually contain tests. It defines the API used for tests.
// It's also used to validate the output generated by fetch-apis (method GenerateServices)

// Do not remove the START line. When comparing with output from GenerateServices,
// only data after that line is matched. So we can write comments like this above it.
//###START###

package apis

// Code generated by fetch-apis; DO NOT EDIT

import "github.com/taskcluster/taskcluster-cli/apis/definitions"

var servicesTest = map[string]definitions.Service{
	"Test": definitions.Service{
		BaseURL:     "http://localhost:8080",
		Title:       "Test API",
		Description: "This is a Test service to test taskcluster-cli",
		Entries: []definitions.Entry{
			definitions.Entry{
				Type:        "function",
				Name:        "test",
				Title:       "Do a test",
				Description: "The server will match the request against a specific format to see if tc-cli works properly.",
				Scopes:      [][]string(nil),
				Stability:   "stable",
				Method:      "get",
				Route:       "/test",
				Args:        []string{},
				Query:       []string{},
				Input:       "",
				Output:      "",
			},
		},
	},
}
var schemasTest = map[string]string{}
