web: cd services/notify && node src/main server
irc: cd services/notify && node src/main irc
handler: cd services/notify && node src/main handler
write-docs: cd services/notify && node src/main writeDocs
