name: Staticcheck
on: pull_request

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  STATICCHECK_VERSION: "2026.1"

jobs:
  staticcheck-gw-multiuser:
    name: Multiuser Engine
    strategy:
      fail-fast: false
      matrix:
        os:  ["windows-latest", "ubuntu-latest", "macOS-latest"]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
      with:
        fetch-depth: 1
        persist-credentials: false
    - uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
      with:
        go-version-file: go.mod
    - uses: dominikh/staticcheck-action@9716614d4101e79b4340dd97b10e54d68234e431 # v1.4.1
      with:
        working-directory: workers/generic-worker
        build-tags: multiuser
        install-go: false
        version: ${{ env.STATICCHECK_VERSION }}

  staticcheck-gw-insecure:
    name: Insecure Engine
    strategy:
      fail-fast: false
      matrix:
        os:  ["ubuntu-latest", "macOS-latest"]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
      with:
        fetch-depth: 1
        persist-credentials: false
    - uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
      with:
        go-version-file: go.mod
    - uses: dominikh/staticcheck-action@9716614d4101e79b4340dd97b10e54d68234e431 # v1.4.1
      with:
        working-directory: workers/generic-worker
        build-tags: insecure
        install-go: false
        version: ${{ env.STATICCHECK_VERSION }}

  staticcheck-go-source:
    name: Go Source
    strategy:
      fail-fast: false
      matrix:
        dir:  ["clients/client-go", "internal", "tools"]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
      with:
        fetch-depth: 1
        persist-credentials: false
    - uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
      with:
        go-version-file: go.mod
    - uses: dominikh/staticcheck-action@9716614d4101e79b4340dd97b10e54d68234e431 # v1.4.1
      with:
        working-directory: ${{ matrix.dir }}
        install-go: false
        version: ${{ env.STATICCHECK_VERSION }}
